/* Whiz by Javier Santo Domingo (j-a-s-d@coderesearchlabs.com) */

package whiz.net;

import whiz.Whiz;

/**
 * Historical and Permanent URI schemes.
 */
public class URISchemes extends Whiz {

	// NOTE: including historical and permanent schemes from https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

	// HISTORICAL

	public static final String FAX = "fax"; // fax [RFC2806][RFC3966]
	public static final String FILESYSTEM = "filesystem"; // historic/filesystem | filesystem [W3C_WebApps_Working_Group][Chris_Rebert]
	public static final String MAILSERVER = "mailserver"; // Access to data available from mail servers [RFC6196]
	public static final String MODEM = "modem"; // modem [RFC2806][RFC3966]
	public static final String PACK = "pack"; // historic/pack | pack [draft-shur-pack-uri-scheme]
	public static final String PROSPERO = "prospero"; // Prospero Directory Service [RFC4157]
	public static final String SNEWS = "snews"; // NNTP over SSL/TLS [RFC5538]
	public static final String VIDEOTEX = "videotex"; // historic/videotex | videotex [draft-mavrakis-videotex-url-spec][RFC2122][RFC3986]
	public static final String WAIS = "wais"; // Wide Area Information Servers [RFC4156]
	public static final String WPID = "wpid"; // prov/wpid | wpid [Eld_Zierau]
	public static final String Z39_50 = "z39.50"; // Z39.50 information access [RFC1738][RFC2056]

	// PERMANENT

	public static final String AAA = "aaa"; // Diameter Protocol [RFC6733]
	public static final String AAAS = "aaas"; // Diameter Protocol with Secure Transport [RFC6733]
	public static final String ABOUT = "about"; // about [RFC6694]
	public static final String ACAP = "acap"; // application configuration access protocol [RFC2244]
	public static final String ACCT = "acct"; // acct [RFC7565]
	public static final String CAP = "cap"; // Calendar Access Protocol [RFC4324]
	public static final String CID = "cid"; // content identifier [RFC2392]
	public static final String COAP = "coap"; // coap [RFC7252]
	public static final String COAP_TCP = "coap+tcp"; // coap+tcp [1] [RFC8323]
	public static final String COAP_WS = "coap+ws"; // coap+ws [1] [RFC8323]
	public static final String COAPS = "coaps"; // coaps [RFC7252]
	public static final String COAPS_TCP = "coaps+tcp"; // coaps+tcp [1] [RFC8323]
	public static final String COAPS_WS = "coaps+ws"; // coaps+ws [1] [RFC8323]
	public static final String CRID = "crid"; // TV-Anytime Content Reference Identifier [RFC4078]
	public static final String DATA = "data"; // data [RFC2397]
	public static final String DAV = "dav"; // dav [RFC4918]
	public static final String DICT = "dict"; // dictionary service protocol [RFC2229]
	public static final String DNS = "dns"; // Domain Name System [RFC4501]
	public static final String EXAMPLE = "example"; // example [RFC7595]
	public static final String FILE = "file"; // Host-specific file names [RFC8089]
	public static final String FTP = "ftp"; // File Transfer Protocol [RFC1738]
	public static final String GEO = "geo"; // Geographic Locations [RFC5870]
	public static final String GO = "go"; // go [RFC3368]
	public static final String GOPHER = "gopher"; // The Gopher Protocol [RFC4266]
	public static final String H323 = "h323"; // H.323 [RFC3508]
	public static final String HTTP = "http"; // Hypertext Transfer Protocol [RFC7230, Section 2.7.1]
	public static final String HTTPS = "https"; // Hypertext Transfer Protocol Secure [RFC7230, Section 2.7.2]
	public static final String IAX = "iax"; // Inter-Asterisk eXchange Version 2 [RFC5456]
	public static final String ICAP = "icap"; // Internet Content Adaptation Protocol [RFC3507]
	public static final String IM = "im"; // Instant Messaging [RFC3860]
	public static final String IMAP = "imap"; // internet message access protocol [RFC5092]
	public static final String INFO = "info"; // Information Assets with Identifiers in Public Namespaces. [RFC4452] (section 3) defines an "info" registry of public namespaces, which is maintained by NISO and can be accessed from [http://info-uri.info/]. [RFC4452]
	public static final String IPP = "ipp"; // Internet Printing Protocol [RFC3510]
	public static final String IPPS = "ipps"; // Internet Printing Protocol over HTTPS [RFC7472]
	public static final String IRIS = "iris"; // Internet Registry Information Service [RFC3981]
	public static final String IRIS_BEEP = "iris.beep"; // iris.beep [RFC3983]
	public static final String IRIS_LWZ = "iris.lwz"; // iris.lwz [RFC4993]
	public static final String IRIS_XPC = "iris.xpc"; // iris.xpc [RFC4992]
	public static final String IRIS_XPCS = "iris.xpcs"; // iris.xpcs [RFC4992]
	public static final String JABBER = "jabber"; // perm/jabber | jabber [Peter_Saint-Andre]
	public static final String LDAP = "ldap"; // Lightweight Directory Access Protocol [RFC4516]
	public static final String MAILTO = "mailto"; // Electronic mail address [RFC6068]
	public static final String MID = "mid"; // message identifier [RFC2392]
	public static final String MSRP = "msrp"; // Message Session Relay Protocol [RFC4975]
	public static final String MSRPS = "msrps"; // Message Session Relay Protocol Secure [RFC4975]
	public static final String MTQP = "mtqp"; // Message Tracking Query Protocol [RFC3887]
	public static final String MUPDATE = "mupdate"; // Mailbox Update (MUPDATE) Protocol [RFC3656]
	public static final String NEWS = "news"; // USENET news [RFC5538]
	public static final String NFS = "nfs"; // network file system protocol [RFC2224]
	public static final String NI = "ni"; // ni [RFC6920]
	public static final String NIH = "nih"; // nih [RFC6920]
	public static final String NNTP = "nntp"; // USENET news using NNTP access [RFC5538]
	public static final String OPAQUELOCKTOKEN = "opaquelocktoken"; // opaquelocktokent [RFC4918]
	public static final String PKCS11 = "pkcs11"; // PKCS#11 [RFC7512]
	public static final String POP = "pop"; // Post Office Protocol v3 [RFC2384]
	public static final String PRES = "pres"; // Presence [RFC3859]
	public static final String RELOAD = "reload"; // reload [RFC6940]
	public static final String RTSP = "rtsp"; // Real-Time Streaming Protocol (RTSP) [RFC2326][RFC7826]
	public static final String RTSPS = "rtsps"; // Real-Time Streaming Protocol (RTSP) over TLS [RFC2326][RFC7826]
	public static final String RTSPU = "rtspu"; // Real-Time Streaming Protocol (RTSP) over unreliable datagram transport [RFC2326]
	public static final String SERVICE = "service"; // service location [RFC2609]
	public static final String SESSION = "session"; // session [RFC6787]
	public static final String SHTTP = "shttp"; // Secure Hypertext Transfer Protocol [RFC2660]
	public static final String SIEVE = "sieve"; // ManageSieve Protocol [RFC5804]
	public static final String SIP = "sip"; // session initiation protocol [RFC3261]
	public static final String SIPS = "sips"; // secure session initiation protocol [RFC3261]
	public static final String SMS = "sms"; // Short Message Service [RFC5724]
	public static final String SNMP = "snmp"; // Simple Network Management Protocol [RFC4088]
	public static final String SOAP_BEEP = "soap.beep"; // soap.beep [RFC4227]
	public static final String SOAP_BEEPS = "soap.beeps"; // soap.beeps [RFC4227]
	public static final String STUN = "stun"; // stun [RFC7064]
	public static final String STUNS = "stuns"; // stuns [RFC7064]
	public static final String TAG = "tag"; // tag [RFC4151]
	public static final String TEL = "tel"; // telephone [RFC3966]
	public static final String TELNET = "telnet"; // Reference to interactive sessions [RFC4248]
	public static final String TFTP = "tftp"; // Trivial File Transfer Protocol [RFC3617]
	public static final String THISMESSAGE = "thismessage"; // perm/thismessage | multipart/related | relative reference resolution [RFC2557]
	public static final String TIP = "tip"; // Transaction Internet Protocol [RFC2371]
	public static final String TN3270 = "tn3270"; // Interactive 3270 emulation sessions [RFC6270]
	public static final String TURN = "turn"; // turn [RFC7065]
	public static final String TURNS = "turns"; // turns [RFC7065]
	public static final String TV = "tv"; // TV Broadcasts [RFC2838]
	public static final String URN = "urn"; // Uniform Resource Names [RFC8141][IANA registry urn-namespaces]
	public static final String VEMMI = "vemmi"; // versatile multimedia interface [RFC2122]
	public static final String VNC = "vnc"; // Remote Framebuffer Protocol [RFC7869]
	public static final String WS = "ws"; // WebSocket connections [RFC6455]
	public static final String WSS = "wss"; // Encrypted WebSocket connections [RFC6455]
	public static final String XCON = "xcon"; // xcon [RFC6501]
	public static final String XCON_USERID = "xcon-userid"; // xcon-userid [RFC6501]
	public static final String XMLRPC_BEEP = "xmlrpc.beep"; // xmlrpc.beep [RFC3529]
	public static final String XMLRPC_BEEPS = "xmlrpc.beeps"; // xmlrpc.beeps [RFC3529]
	public static final String XMPP = "xmpp"; // Extensible Messaging and Presence Protocol [RFC5122]
	public static final String Z39_50R = "z39.50r"; // Z39.50 Retrieval [RFC2056]
	public static final String Z39_50S = "z39.50s"; // Z39.50 Session [RFC2056]

}
